# .github/workflows/pgtest.yml
name: Postgres tests

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@main
      - name: build application
        run: make build

  pgtap:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pg-version: [ '16' ]

    container: pgxn/pgxn-tools
    env:
      PGUSER: postgres

    steps:

      - name: install extension
        run: make install

      - name: load sql
        run: >-
          psql --host localhost --username postgres --dbname postgres \
               -c 'select name,default_version,installed_version from pg_available_extensions order by name'
        env:
          PGPASSWORD: postgres

      - name: load sql
        run: >-
          psql --host localhost --username postgres --dbname postgres \
               -c 'CREATE EXTENSION ddl_historization'
        env:
          PGPASSWORD: postgres

      - name: run tests
        run: pg_prove --host localhost --dbname postgres --username postgres *_test.sql
        env:
          PGPASSWORD: postgres
